package com.taxedge.messaging.entity;

import java.time.LocalDateTime;

import com.taxedge.customer.entity.Customer;
import com.taxedge.messaging.enums.RoomStatus;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.ForeignKey;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Represents a chat room between one Customer and one assigned CA accountant.
 * A customer can only have ONE open room at a time.
 * A CA can have MULTIPLE open rooms (up to their max_chats limit).
 *
 * DB table: chat_rooms
 */
@Entity
@Table(name = "chat_rooms")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Conversation {

    /**
     * Format: ROOM-{custId}-{caId}
     * Example: ROOM-CUST001-CA003
     * Generated by service before save.
     */
    @Id
    @Column(name = "room_id", length = 100, nullable = false, updatable = false)
    private String roomId;

    /**
     * The customer who initiated the chat.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(
        name = "cust_id",
        referencedColumnName = "cust_id",
        nullable = false,
        updatable = false,
        foreignKey = @ForeignKey(name = "fk_chat_room_customer")
    )
    private Customer customer;

    /**
     * The CA accountant assigned to handle this chat.
     * Stored as a plain String (caId) to avoid tight coupling
     * until the Employee entity is fully implemented.
     */
    @Column(name = "ca_id", length = 50, nullable = false)
    private String caId;

    /**
     * Display name of the CA (denormalized for fast display).
     */
    @Column(name = "ca_name", length = 100)
    private String caName;

    /**
     * Current state of this room.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private RoomStatus status;

    /**
     * When was this room created.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * When was this room closed or transferred (nullable).
     */
    @Column(name = "closed_at")
    private LocalDateTime closedAt;

    /**
     * If transferred, which CA received the room.
     */
    @Column(name = "transferred_to_ca_id", length = 50)
    private String transferredToCaId;

    @PrePersist
    void onCreate() {
        this.createdAt = LocalDateTime.now();
        if (this.status == null) {
            this.status = RoomStatus.OPEN;
        }
    }
}
