package com.taxedge.loan.enums;

public enum LoanPurpose {
    BUSINESS_EXPANSION,
    WORKING_CAPITAL_INVENTORY,
    MACHINERY_EQUIPMENT_PURCHASE,
    HOME_PURCHASE_CONSTRUCTION,
    HOME_RENOVATION,
    VEHICLE_PURCHASE,
    DEBT_CONSOLIDATION,
    PERSONAL_MEDICAL_EMERGENCY
}