import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { padding: 16, backgroundColor: '#F8FAFC' },
  heading: { fontSize: 20, fontWeight: '700', color: '#083B75', marginBottom: 4 },
  subheading: { fontSize: 13, color: '#64748B', marginBottom: 20, lineHeight: 18 },
  card: { backgroundColor: '#FFFFFF', borderRadius: 12, borderWidth: 1, borderColor: '#E2E8F0', marginBottom: 16, overflow: 'hidden' },
  cardHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 14, backgroundColor: '#F1F5F9' },
  cardHeaderLeft: { flexDirection: 'row', alignItems: 'center', gap: 10, flex: 1 },
  avatarBox: { width: 34, height: 34, borderRadius: 17, backgroundColor: '#083B75', alignItems: 'center', justifyContent: 'center' },
  avatarText: { color: '#FFFFFF', fontWeight: '700', fontSize: 13 },
  cardTitleGroup: { flex: 1 },
  cardTitle: { fontSize: 14, fontWeight: '700', color: '#083B75' },
  cardSubtitle: { fontSize: 12, color: '#64748B', marginTop: 1 },
  cardHeaderRight: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  editBtnHeader: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: '#EFF6FF', borderColor: '#BFDBFE', borderWidth: 1, paddingHorizontal: 8, paddingVertical: 5, borderRadius: 6 },
  editBtnHeaderText: { fontSize: 12, fontWeight: '600', color: '#083B75' },
  deleteBtnHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#FEF2F2', borderColor: '#FCA5A5', borderWidth: 1, paddingHorizontal: 8, paddingVertical: 5, borderRadius: 6 },
  summaryBox: { padding: 12, backgroundColor: '#FFFFFF', gap: 6 },
  summaryRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  summaryText: { fontSize: 12, color: '#475569' },
  summaryBold: { fontWeight: '700', color: '#0F172A' },
  cardContent: { padding: 16 },
  sectionTitle: { fontSize: 14, fontWeight: '700', color: '#083B75', marginTop: 6, marginBottom: 10 },
  sectionDivider: { height: 1, backgroundColor: '#E2E8F0', marginVertical: 14 },
  fieldGroup: { marginBottom: 12 },
  label: { fontSize: 12, fontWeight: '600', color: '#334155', marginBottom: 4 },
  input: { backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#CBD5E1', borderRadius: 8, paddingHorizontal: 12, paddingVertical: 8, fontSize: 13, color: '#0F172A' },
  row: { flexDirection: 'row', gap: 10 },
  halfField: { flex: 1 },
  chipRow: { flexDirection: 'row', gap: 10, marginTop: 4 },
  chip: { flex: 1, paddingVertical: 8, borderRadius: 6, borderWidth: 1, borderColor: '#CBD5E1', backgroundColor: '#FFFFFF', alignItems: 'center', justifyContent: 'center' },
  chipSelected: { borderColor: '#083B75', backgroundColor: '#083B75' },
  chipText: { fontSize: 13, fontWeight: '500', color: '#334155' },
  chipTextSelected: { color: '#FFFFFF', fontWeight: '600' },
  checkboxRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginVertical: 8 },
  checkboxText: { fontSize: 12, color: '#334155', fontWeight: '500', flex: 1 },
  readOnlyBox: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: '#F1F5F9', borderWidth: 1, borderColor: '#CBD5E1', borderRadius: 8, paddingHorizontal: 12, paddingVertical: 10 },
  readOnlyText: { fontSize: 14, fontWeight: '700', color: '#083B75' },
  cardActionsRow: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10, marginTop: 16 },
  cancelFormBtn: { paddingHorizontal: 16, paddingVertical: 10, borderRadius: 8, borderWidth: 1, borderColor: '#CBD5E1', backgroundColor: '#FFFFFF' },
  cancelFormText: { fontSize: 13, fontWeight: '600', color: '#475569' },
  saveFormBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 18, paddingVertical: 10, borderRadius: 8, backgroundColor: '#083B75' },
  saveFormText: { fontSize: 13, fontWeight: '600', color: '#FFFFFF' },
  addBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, backgroundColor: '#EFF6FF', borderWidth: 1, borderColor: '#BFDBFE', borderRadius: 8, paddingVertical: 12, marginTop: 8, marginBottom: 24 },
  addBtnText: { fontSize: 14, fontWeight: '600', color: '#083B75' },
  dropdownButton: { backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#CBD5E1', borderRadius: 8, paddingHorizontal: 12, paddingVertical: 8, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', height: 38 },
  dropdownButtonText: { fontSize: 13, color: '#0F172A' },
  placeholderText: { color: '#94A3B8' },
  dropdownMenu: { backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#CBD5E1', borderRadius: 8, marginTop: 4, overflow: 'hidden', elevation: 4, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4 },
  dropdownItem: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 12, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: '#F1F5F9' },
  dropdownItemActive: { backgroundColor: '#F0F7FF' },
  dropdownItemText: { fontSize: 13, color: '#334155' },
  dropdownItemTextActive: { color: '#083B75', fontWeight: '600' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(15, 23, 42, 0.5)', justifyContent: 'center', alignItems: 'center', padding: 20 },
  modalCard: { width: '100%', maxWidth: 340, backgroundColor: '#FFFFFF', borderRadius: 14, padding: 20, alignItems: 'center', elevation: 5 },
  modalHeaderIcon: { width: 48, height: 48, borderRadius: 24, backgroundColor: '#FEF2F2', alignItems: 'center', justifyContent: 'center', marginBottom: 12 },
  modalTitle: { fontSize: 16, fontWeight: '700', color: '#0F172A', marginBottom: 6, textAlign: 'center' },
  modalMessage: { fontSize: 13, color: '#64748B', textAlign: 'center', lineHeight: 18, marginBottom: 20 },
  modalActions: { flexDirection: 'row', gap: 12, width: '100%' },
  modalCancelBtn: { flex: 1, paddingVertical: 10, borderRadius: 8, borderWidth: 1, borderColor: '#CBD5E1', backgroundColor: '#FFFFFF', alignItems: 'center' },
  modalCancelText: { fontSize: 13, fontWeight: '600', color: '#475569' },
  modalDeleteBtn: { flex: 1, paddingVertical: 10, borderRadius: 8, backgroundColor: '#EF4444', alignItems: 'center' },
  modalDeleteText: { fontSize: 13, fontWeight: '600', color: '#FFFFFF' },
  inputError: { borderColor: '#EF4444' },
  errorText: { fontSize: 12, color: '#EF4444', marginTop: 4, fontWeight: '500' },
});
