import { StyleSheet, type Insets } from "react-native";
import { BrandColors, Typography, Spacing, BorderRadius } from "@/shared/theme";

export const previewModalColors = {
  documentIcon: BrandColors.PRIMARY_ORANGE,
  closeIcon: BrandColors.TEXT_SECONDARY,
  verifiedIcon: "#166534",
  shareIcon: BrandColors.PRIMARY_ORANGE_DARK,
} as const;

export const closeButtonHitSlop: Insets = { top: 10, bottom: 10, left: 10, right: 10 };

export const styles = StyleSheet.create({
  // --- ITR Variant Styles ---
  overlay: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.75)",
    justifyContent: "center",
    alignItems: "center",
    padding: Spacing.lg,
  },
  contentContainer: {
    width: "100%",
    maxWidth: 420,
    backgroundColor: "#FFFFFF",
    borderRadius: BorderRadius.lg,
    padding: Spacing.lg,
    maxHeight: "85%",
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: Spacing.md,
    paddingBottom: Spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
  },
  titleCol: {
    flex: 1,
    marginRight: Spacing.sm,
  },
  docTitle: {
    fontSize: Typography.fontSize.base,
    fontWeight: Typography.fontWeight.bold,
    color: BrandColors.TEXT_PRIMARY,
  },
  docMeta: {
    fontSize: Typography.fontSize.xs,
    color: BrandColors.TEXT_MUTED,
    marginTop: 2,
  },
  closeBtn: {
    padding: Spacing.xs,
  },
  previewBox: {
    width: "100%",
    height: 320,
    backgroundColor: "#F8FAFC",
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
    marginBottom: Spacing.lg,
  },
  previewImage: {
    width: "100%",
    height: "100%",
  },
  pdfCard: {
    alignItems: "center",
    padding: Spacing.lg,
  },
  pdfTitle: {
    fontSize: Typography.fontSize.base,
    fontWeight: Typography.fontWeight.semiBold,
    color: BrandColors.TEXT_PRIMARY,
    marginTop: Spacing.md,
    textAlign: "center",
  },
  pdfSubtitle: {
    fontSize: Typography.fontSize.xs,
    color: BrandColors.TEXT_SECONDARY,
    marginTop: Spacing.xs,
  },
  pdfVerifiedBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#DCFCE7",
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.xs,
    borderRadius: BorderRadius.full,
    marginTop: Spacing.lg,
    gap: Spacing.xs,
  },
  pdfVerifiedText: {
    fontSize: Typography.fontSize.xs,
    fontWeight: Typography.fontWeight.medium,
    color: "#166534",
  },
  actionsRow: {
    flexDirection: "row",
    gap: Spacing.md,
  },
  changeBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#EAF1FE",
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius.md,
    gap: Spacing.xs,
  },
  changeBtnText: {
    fontSize: Typography.fontSize.sm,
    fontWeight: Typography.fontWeight.semiBold,
    color: "#083B75",
  },
  doneBtn: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: BrandColors.PRIMARY_ORANGE,
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius.md,
  },
  doneBtnText: {
    fontSize: Typography.fontSize.sm,
    fontWeight: Typography.fontWeight.bold,
    color: "#FFFFFF",
  },

  // --- Loans Variant Styles ---
  backdrop: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.65)",
    justifyContent: "center",
    alignItems: "center",
    padding: Spacing.base,
  },
  modalContainer: {
    width: "100%",
    maxWidth: 420,
    backgroundColor: BrandColors.WHITE,
    borderRadius: BorderRadius.lg,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 8,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: Spacing.base,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: BrandColors.CARD_BORDER,
    backgroundColor: BrandColors.WHITE,
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    flex: 1,
    marginRight: Spacing.sm,
  },
  title: {
    fontSize: Typography.fontSize.sm,
    fontWeight: Typography.fontWeight.bold,
    color: BrandColors.TEXT_PRIMARY,
    flex: 1,
  },
  content: {
    padding: Spacing.base,
    alignItems: "center",
  },
  imagePreview: {
    width: "100%",
    height: 320,
    borderRadius: BorderRadius.sm,
    backgroundColor: BrandColors.BACKGROUND,
  },
  docCard: {
    width: "100%",
    alignItems: "center",
    paddingVertical: Spacing.lg,
    paddingHorizontal: Spacing.base,
    borderRadius: BorderRadius.md,
    backgroundColor: BrandColors.BACKGROUND,
    borderWidth: 1,
    borderColor: BrandColors.BORDER,
  },
  iconCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: BrandColors.PRIMARY_LIGHT_ORANGE,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: Spacing.md,
  },
  fileName: {
    fontSize: Typography.fontSize.sm,
    fontWeight: Typography.fontWeight.bold,
    color: BrandColors.TEXT_PRIMARY,
    textAlign: "center",
    marginBottom: Spacing.xs,
  },
  fileMeta: {
    fontSize: Typography.fontSize.xs,
    color: BrandColors.TEXT_SECONDARY,
    textAlign: "center",
    marginBottom: Spacing.md,
  },
  statusBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: Spacing.xs,
    borderRadius: BorderRadius.md,
    backgroundColor: "#DCFCE7",
    marginBottom: Spacing.base,
  },
  statusText: {
    fontSize: Typography.fontSize.xs - 1,
    fontWeight: Typography.fontWeight.semiBold,
    color: "#166534",
  },
  shareBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: Spacing.base,
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: BrandColors.PRIMARY_ORANGE,
    backgroundColor: BrandColors.WHITE,
  },
  shareBtnText: {
    fontSize: Typography.fontSize.xs,
    fontWeight: Typography.fontWeight.bold,
    color: BrandColors.PRIMARY_ORANGE_DARK,
  },
  footer: {
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.md,
    borderTopWidth: 1,
    borderTopColor: BrandColors.CARD_BORDER,
    backgroundColor: BrandColors.WHITE,
  },
  closeActionBtn: {
    width: "100%",
    paddingVertical: 11,
    borderRadius: BorderRadius.sm,
    backgroundColor: BrandColors.CARD_BORDER,
    alignItems: "center",
    justifyContent: "center",
  },
  closeActionText: {
    fontSize: Typography.fontSize.sm,
    fontWeight: Typography.fontWeight.semiBold,
    color: "#475569",
  },

  // --- Project Finance Variant Styles ---
  pfOverlay: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.6)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  pfCloseBtn: {
    padding: 4,
  },
  pfContainer: {
    width: "100%",
    maxWidth: 380,
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 8,
  },
  pfHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
    backgroundColor: "#F8FAFC",
  },
  pfTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#0F172A",
  },
  pfBody: {
    padding: 18,
    alignItems: "center",
  },
  pfBadge: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#EFF6FF",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  pfDocTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#1E293B",
    textAlign: "center",
  },
  pfFileName: {
    fontSize: 13,
    color: "#64748B",
    marginTop: 4,
    textAlign: "center",
  },
  pfMetaBox: {
    width: "100%",
    backgroundColor: "#F8FAFC",
    borderRadius: 10,
    padding: 12,
    marginTop: 16,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    gap: 8,
  },
  pfMetaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  pfMetaLabel: {
    fontSize: 12,
    color: "#64748B",
  },
  pfMetaValue: {
    fontSize: 12,
    fontWeight: "600",
    color: "#0F172A",
  },
  pfStatusVerified: {
    fontSize: 12,
    fontWeight: "700",
    color: "#16A34A",
  },
  pfFooter: {
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderTopWidth: 1,
    borderTopColor: "#F1F5F9",
    backgroundColor: "#FAFAFA",
  },
  pfCloseActionBtn: {
    backgroundColor: "#0B1B36",
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  pfCloseActionText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "600",
  },
});
