import { StyleSheet } from "react-native";
import {
  BrandColors,
  BorderRadius,
  Spacing,
  Typography,
} from "@/shared/theme";

export const reviewStyles = StyleSheet.create({
  reviewMetaCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: BorderRadius.base + 2,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    padding: 16,
    gap: 12,
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 4,
    elevation: 1,
  },
  reviewMetaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  reviewMetaKey: {
    fontSize: Typography.fontSize.sm + 0.5,
    color: "#64748B",
    fontWeight: "500",
  },
  reviewMetaVal: {
    fontSize: Typography.fontSize.sm + 1,
    color: "#0F172A",
    fontWeight: "700",
  },
  reviewMetaDivider: {
    height: 1,
    backgroundColor: "#F1F5F9",
  },
  requestedDetailsCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: BorderRadius.base + 2,
    borderWidth: 1.5,
    borderColor: "#FFD8BF",
    padding: 16,
    gap: 10,
  },
  requestedCardHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  requestedCardTitle: {
    fontSize: Typography.fontSize.sm,
    fontWeight: "800",
    color: BrandColors.PRIMARY_ORANGE_DARK,
    letterSpacing: 0.5,
  },
  editOptionBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#FFF1E8",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: "#FED7AA",
  },
  editOptionText: {
    fontSize: Typography.fontSize.xs + 1.5,
    fontWeight: "700",
    color: BrandColors.PRIMARY_ORANGE,
  },
  reviewFieldRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingVertical: 4,
    gap: 12,
  },
  reviewFieldLabel: {
    fontSize: Typography.fontSize.sm,
    color: "#64748B",
    fontWeight: "500",
    flex: 1,
  },
  reviewFieldValue: {
    fontSize: Typography.fontSize.sm,
    color: "#0F172A",
    fontWeight: "700",
    flex: 1.4,
    textAlign: "right",
  },
  reviewDocsCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: BorderRadius.base + 2,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    padding: 16,
    gap: 10,
  },
  reviewDocsTitle: {
    fontSize: Typography.fontSize.base,
    fontWeight: "800",
    color: "#0F172A",
  },
  reviewDocRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  reviewDocName: {
    fontSize: Typography.fontSize.sm + 0.5,
    color: "#334155",
    fontWeight: "500",
    flex: 1,
  },
  reviewDocSize: {
    fontSize: Typography.fontSize.sm,
    color: "#0F172A",
    fontWeight: "700",
    marginLeft: 12,
  },
  declarationBox: {
    flexDirection: "row",
    alignItems: "flex-start",
    backgroundColor: "#EAF1FE",
    borderRadius: BorderRadius.base,
    borderWidth: 1,
    borderColor: "#BFDBFE",
    padding: 14,
    gap: 12,
    marginTop: 4,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1.8,
    borderColor: "#083B75",
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 1,
  },
  checkboxActive: {
    backgroundColor: "#083B75",
    borderColor: "#083B75",
  },
  declarationText: {
    flex: 1,
    fontSize: Typography.fontSize.sm,
    color: "#083B75",
    fontWeight: "500",
    lineHeight: 20,
  },
  successContainer: {
    flex: 1,
    backgroundColor: "#F8FAFC",
  },
  successHero: {
    backgroundColor: BrandColors.PRIMARY_BLUE,
    borderBottomLeftRadius: 36,
    borderBottomRightRadius: 36,
    alignItems: "center",
    paddingBottom: 42,
  },
  successHeroIconBox: {
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
  },
  successHeroCheckCircle: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: BrandColors.PRIMARY_ORANGE,
    justifyContent: "center",
    alignItems: "center",
  },
  successHeroTitle: {
    fontSize: Typography.fontSize.hero - 1,
    fontWeight: "900",
    color: "#FFFFFF",
    letterSpacing: -0.3,
  },
  successCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    marginHorizontal: Spacing.base,
    marginTop: -22,
    padding: 22,
    gap: 16,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 14,
    elevation: 4,
  },
  successRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  successRowKey: {
    fontSize: Typography.fontSize.sm + 1,
    color: "#64748B",
    fontWeight: "500",
  },
  successRowVal: {
    fontSize: Typography.fontSize.base,
    color: "#0F172A",
    fontWeight: "800",
  },
  successDivider: {
    height: 1,
    backgroundColor: "#F1F5F9",
  },
  successActionsWrap: {
    backgroundColor: "#F8FAFC",
    paddingHorizontal: Spacing.base,
    paddingTop: 16,
    gap: 12,
    borderTopWidth: 1,
    borderTopColor: "#E2E8F0",
  },
  modalScrollView: {
    flex: 1,
  },
  modalScrollContent: {
    paddingBottom: 24,
  },
});
