import { StyleSheet, Platform } from "react-native";
import {
  BrandColors,
  BorderRadius,
  Typography,
} from "@/shared/theme";

export const formStyles = StyleSheet.create({
  editContainer: {
    gap: 18,
    marginTop: 4,
  },
  currentRegisteredCard: {
    backgroundColor: "#F1F5F9",
    borderRadius: BorderRadius.base,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    padding: 16,
    gap: 12,
  },
  currentRegisteredHeader: {
    fontSize: Typography.fontSize.sm + 1,
    fontWeight: "800",
    color: "#0F172A",
  },
  currentRegisteredSubtitle: {
    fontSize: Typography.fontSize.xs + 1,
    fontWeight: "500",
    color: "#64748B",
  },
  currentFieldRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingTop: 4,
  },
  currentFieldLabel: {
    fontSize: Typography.fontSize.sm,
    color: "#64748B",
    fontWeight: "500",
    flex: 1,
  },
  currentFieldValue: {
    fontSize: Typography.fontSize.sm + 0.5,
    color: "#0F172A",
    fontWeight: "700",
    flex: 1.5,
    textAlign: "right",
  },
  formSectionTitle: {
    fontSize: Typography.fontSize.lg,
    fontWeight: "800",
    color: "#0F172A",
    marginTop: 4,
    marginBottom: -6,
  },
  fieldGroup: {
    gap: 6,
  },
  fieldLabel: {
    fontSize: Typography.fontSize.sm + 1,
    fontWeight: "700",
    color: "#0F172A",
  },
  input: {
    height: 50,
    backgroundColor: "#FFFFFF",
    borderRadius: BorderRadius.base,
    borderWidth: 1.5,
    borderColor: "#CBD5E1",
    paddingHorizontal: 14,
    fontSize: Typography.fontSize.base,
    color: "#0F172A",
    fontWeight: "500",
  },
  inputError: {
    borderColor: "#EF4444",
    backgroundColor: "#FEF2F2",
  },
  dropdownSelect: {
    height: 50,
    backgroundColor: "#FFFFFF",
    borderRadius: BorderRadius.base,
    borderWidth: 1.5,
    borderColor: "#CBD5E1",
    paddingHorizontal: 14,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  dropdownSelectText: {
    fontSize: Typography.fontSize.base,
    color: "#0F172A",
    fontWeight: "500",
  },
  dropdownPlaceholderText: {
    fontSize: Typography.fontSize.base,
    color: "#94A3B8",
    fontWeight: "500",
  },
  fieldCounterRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginTop: 4,
  },
  fieldCounterText: {
    fontSize: Typography.fontSize.xs + 1,
    color: "#94A3B8",
    fontWeight: "500",
  },
  proofCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: BorderRadius.base + 2,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    padding: 16,
    gap: 14,
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 4,
    elevation: 1,
  },
  proofDescText: {
    fontSize: Typography.fontSize.sm,
    color: "#64748B",
    lineHeight: 20,
  },
  uploadActionsRow: {
    flexDirection: "row",
    gap: 12,
  },
  uploadBtn: {
    flex: 1,
    height: 48,
    borderRadius: BorderRadius.base,
    borderWidth: 1.5,
    borderColor: "#083B75",
    backgroundColor: "#FFFFFF",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  uploadBtnText: {
    fontSize: Typography.fontSize.sm + 1,
    fontWeight: "700",
    color: "#083B75",
  },
  proofErrorText: {
    fontSize: Typography.fontSize.sm,
    color: "#DC2626",
    fontWeight: "500",
  },
  docPreviewRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F8FAFC",
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    padding: 12,
  },
  docPreviewIcon: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: "#EAF1FE",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
  },
  docPreviewInfo: {
    flex: 1,
  },
  docPreviewName: {
    fontSize: Typography.fontSize.sm + 0.5,
    fontWeight: "700",
    color: "#0F172A",
  },
  docPreviewSize: {
    fontSize: Typography.fontSize.xs + 1,
    color: "#64748B",
    marginTop: 2,
  },
  docDeleteBtn: {
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  docDeleteText: {
    fontSize: Typography.fontSize.sm,
    fontWeight: "700",
    color: "#DC2626",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.5)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: Platform.OS === "ios" ? 36 : 24,
    maxHeight: "75%",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
  },
  modalTitle: {
    fontSize: Typography.fontSize.md + 1,
    fontWeight: "800",
    color: "#0F172A",
  },
  modalCloseBtn: {
    padding: 4,
  },
  modalOptionItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#F8FAFC",
  },
  modalOptionText: {
    fontSize: Typography.fontSize.base,
    color: "#334155",
    fontWeight: "500",
  },
  modalOptionSelectedText: {
    color: BrandColors.PRIMARY_BLUE,
    fontWeight: "700",
  },
  phoneInputWrap: {
    flexDirection: "row",
    alignItems: "center",
    height: 50,
    backgroundColor: "#FFFFFF",
    borderRadius: BorderRadius.base,
    borderWidth: 1.5,
    borderColor: "#CBD5E1",
    overflow: "hidden",
  },
  phonePrefixBox: {
    height: "100%",
    paddingHorizontal: 14,
    backgroundColor: "#F1F5F9",
    borderRightWidth: 1,
    borderRightColor: "#CBD5E1",
    justifyContent: "center",
    alignItems: "center",
  },
  phonePrefixText: {
    fontSize: Typography.fontSize.base,
    fontWeight: "700",
    color: "#0F172A",
  },
  phoneTextInput: {
    flex: 1,
    height: "100%",
    paddingHorizontal: 14,
    fontSize: Typography.fontSize.base,
    color: "#0F172A",
    fontWeight: "500",
  },
  dateInputWrap: {
    flexDirection: "row",
    alignItems: "center",
    height: 50,
    backgroundColor: "#FFFFFF",
    borderRadius: BorderRadius.base,
    borderWidth: 1.5,
    borderColor: "#CBD5E1",
    paddingHorizontal: 14,
  },
  dateTextInput: {
    flex: 1,
    height: "100%",
    fontSize: Typography.fontSize.base,
    color: "#0F172A",
    fontWeight: "500",
  },
  dateIconBox: {
    marginLeft: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  acceptedProofsCard: {
    backgroundColor: "#FFF7ED",
    borderRadius: BorderRadius.base + 2,
    borderWidth: 1,
    borderColor: "#FFEDD5",
    padding: 16,
    marginTop: 14,
  },
  acceptedProofsHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
    gap: 8,
  },
  acceptedProofsTitle: {
    fontSize: Typography.fontSize.base,
    fontWeight: "700",
    color: "#0F172A",
  },
  acceptedProofList: {
    marginTop: 2,
  },
  acceptedProofItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 6,
    paddingRight: 4,
  },
  acceptedProofDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: BrandColors.PRIMARY_ORANGE,
    marginTop: 7,
    marginRight: 8,
  },
  acceptedProofText: {
    flex: 1,
    fontSize: 13.5,
    color: "#334155",
    lineHeight: 20,
    fontWeight: "400",
  },
  viewMoreBtn: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-end",
    marginTop: 6,
    paddingVertical: 4,
    paddingHorizontal: 2,
    gap: 4,
  },
  viewMoreText: {
    fontSize: Typography.fontSize.sm,
    fontWeight: "700",
    color: BrandColors.PRIMARY_ORANGE,
  },
});
