spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taxedge
    username: root
    password: shashi/4274

#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true

#spring:
 # datasource:
  #  url: jdbc:postgresql://localhost:5432/taxedge
   # username: postgres
    #password: Srini123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 150MB
