spring:
  application:
    name: taxedge-backend

  profiles:
    active: dev

  flyway:
    enabled: true
    locations: classpath:db/migration


server:
  port: 8086

  error:
    include-message: always


jwt:
  secret: 7fK9mQ2xV8pL4zR6tY13sH8jA0eB6uI9oP2vX4kG7nM5qZ1rT8
  expiration: 3600000    # 3 minutes for testing


# ===============================
# ACTUATOR
# ===============================

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  endpoint:
    health:
      show-details: always
      show-components: always

    prometheus:
      enabled: true

  metrics:
    tags:
      application: ${spring.application.name}


logging:
  level:
    com.taxedge: DEBUG